SET SERVEROUTPUT ON;
DECLARE
	PROCEDURE comm
	IS 
	c NUMBER;
	n VARCHAR2(20);
	BEGIN
		n:='&empname';
		UPDATE EMPLOYEE SET COMMISION=COMMISION+((COMMISION*5)/100) WHERE EMPNAME=N;
	END;
	BEGIN
		comm();
	END; 
